🎯 Extra Missions

Here I share my extra missions for this mod:  
👉 [Expansion Quests (Steam Workshop)](https://steamcommunity.com/sharedfiles/filedetails/?id=3277130230)

Feel free to use them on your own server.  
Everything is tested and ready to go.

Enjoy! 🎉
